### ISSUE TITLE
Code Editor error in Fireball distribution

### ISSUE THREAD

**Issue by nantas** [fireball-packages/code-editor#8]
While opening code editor in Fireball Distribution:
```js
Error: ENOENT: no such file or directory, lstat '/Users/nantas/projects/fireball-x/fireball/dist/Fireball.app/Contents/Resources/app/utils'
    at Error (native)
```

If keep typing:

```js
TypeError: Cannot read property 'get' of undefined
    at getCompletions (packages://code-editor/panel/codemirror/addon/hint/javascript-hint.js:147:39)
    at scriptHint (packages://code-editor/panel/codemirror/addon/hint/javascript-hint.js:57:19)
    at Array.javascriptHint (packages://code-editor/panel/codemirror/addon/hint/javascript-hint.js:63:12)
    at Object.hint (packages://code-editor/panel/codemirror/addon/hint/show-hint.js:388:29)
    at Object.Completion._update (packages://code-editor/panel/codemirror/addon/hint/show-hint.js:128:33)
    at Object.Completion.update (packages://code-editor/panel/codemirror/addon/hint/show-hint.js:116:12)
    at packages://code-editor/panel/codemirror/addon/hint/show-hint.js:101:64
```

**Comment by yorkie** [comment]
Hey @nantas Does the distribution also execute this line: https://github.com/fireball-x/fireball/blob/master/gulpfile.js#L118, namely the gulp task `cp-apisrc`

**Comment by nantas** [comment]
ah, I forgot about that. I'll try and paste result.

**Comment by yorkie** [comment]
Thanks :)

**Comment by yorkie** [comment]
@nantas does this get working? something could i help with you?
